name: Herobrine
main: com.steaks4uce.Herobrine.Herobrine
author: steaks4uce
version: 1.6
description: Hes watching... and waiting.
commands:
  hb:
    description: Various action commands
    usage: /hb
